#pragma checksum "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "6a31053f7eb0760194c4d3d82b6e0bdc8c5e019d5a21f0f3f9b631e46410e9ab"
// <auto-generated/>
#pragma warning disable 1591
namespace 
#nullable restore
#line (1,12)-(1,30) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Alife.Function.Mcp

#line default
#line hidden
#nullable disable
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
#nullable restore
#line (3,2)-(3,17) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
using AntDesign

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class McpServiceUI : 
#nullable restore
#line (2,11)-(2,68) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Alife.Framework.ModuleUIBase<McpService, McpServerConfig>

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "div");
            __builder.AddAttribute(1, "style", "background: #fff; padding: 20px; border-radius: 8px;");
            __builder.OpenComponent<global::AntDesign.Flex>(2);
            __builder.AddComponentParameter(3, nameof(global::AntDesign.Flex.
#nullable restore
#line (6,11)-(6,18) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Justify

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::OneOf.OneOf<global::AntDesign.FlexJustify, global::System.String>>(
#nullable restore
#line (6,22)-(6,46) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
FlexJustify.SpaceBetween

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(4, nameof(global::AntDesign.Flex.
#nullable restore
#line (6,49)-(6,54) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Align

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::OneOf.OneOf<global::AntDesign.FlexAlign, global::System.String>>(
#nullable restore
#line (6,58)-(6,74) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
FlexAlign.Center

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(5, nameof(global::AntDesign.Flex.
#nullable restore
#line (6,77)-(6,82) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Style

#line default
#line hidden
#nullable disable
            ), "margin-bottom: 24px;");
            __builder.AddAttribute(6, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder2) => {
                __builder2.OpenComponent<global::AntDesign.Title>(7);
                __builder2.AddComponentParameter(8, nameof(global::AntDesign.Title.
#nullable restore
#line (7,16)-(7,21) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Level

#line default
#line hidden
#nullable disable
                ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Int32>(
#nullable restore
#line (7,23)-(7,24) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
4

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddComponentParameter(9, nameof(global::AntDesign.Title.
#nullable restore
#line (7,26)-(7,31) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Style

#line default
#line hidden
#nullable disable
                ), "margin: 0;");
                __builder2.AddAttribute(10, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder3) => {
                    __builder3.AddMarkupContent(11, "MCP 服务器管理");
                }
                ));
                __builder2.CloseComponent();
                __builder2.AddMarkupContent(12, "\n        ");
                __builder2.OpenComponent<global::AntDesign.Button>(13);
                __builder2.AddComponentParameter(14, nameof(global::AntDesign.Button.
#nullable restore
#line (8,17)-(8,21) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Type

#line default
#line hidden
#nullable disable
                ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.ButtonType?>(
#nullable restore
#line (8,24)-(8,42) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
ButtonType.Primary

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddComponentParameter(15, nameof(global::AntDesign.Button.
#nullable restore
#line (8,44)-(8,51) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
OnClick

#line default
#line hidden
#nullable disable
                ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::Microsoft.AspNetCore.Components.Web.MouseEventArgs>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line (8,53)-(8,62) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
AddServer

#line default
#line hidden
#nullable disable
                )));
                __builder2.AddAttribute(16, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder3) => {
                    __builder3.AddMarkupContent(17, "添加服务器");
                }
                ));
                __builder2.CloseComponent();
            }
            ));
            __builder.CloseComponent();
            __builder.AddMarkupContent(18, "\n\n    ");
            __builder.OpenComponent<global::AntDesign.Table<
#nullable restore
#line (11,19)-(11,32) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
McpServerItem

#line default
#line hidden
#nullable disable
            >>(19);
            __builder.AddComponentParameter(20, nameof(global::AntDesign.Table<McpServerItem>.
#nullable restore
#line (11,34)-(11,44) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
DataSource

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEnumerable<McpServerItem>>(
#nullable restore
#line (11,47)-(11,68) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Configuration.Servers

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(21, nameof(global::AntDesign.Table<McpServerItem>.
#nullable restore
#line (11,70)-(11,78) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Bordered

#line default
#line hidden
#nullable disable
            ), true);
            __builder.AddComponentParameter(22, nameof(global::AntDesign.Table<McpServerItem>.
#nullable restore
#line (11,79)-(11,83) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Size

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.TableSize>(
#nullable restore
#line (11,86)-(11,101) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
TableSize.Small

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(23, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment<McpServerItem>)((context) => (__builder2) => {
                global::__Blazor.Alife.Function.Mcp.McpServiceUI.TypeInference.CreatePropertyColumn_0(__builder2, 24, default(McpServerItem)!, 25, 
#nullable restore
#line (12,35)-(12,44) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
c=>c.Name

#line default
#line hidden
#nullable disable
                , 26, "名称");
                __builder2.AddMarkupContent(27, "\n        ");
                global::__Blazor.Alife.Function.Mcp.McpServiceUI.TypeInference.CreatePropertyColumn_1(__builder2, 28, default(McpServerItem)!, 29, 
#nullable restore
#line (13,35)-(13,51) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
c=>c.IsUrlServer

#line default
#line hidden
#nullable disable
                , 30, "类型", 31, (__builder3) => {
#nullable restore
#line (14,15)-(14,54) 26 "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
__builder3.AddContent(32, context.IsUrlServer ? "URL 服务" : "本地命令"

#line default
#line hidden
#nullable disable
                    );
                }
                );
                __builder2.AddMarkupContent(33, "\n        ");
                global::__Blazor.Alife.Function.Mcp.McpServiceUI.TypeInference.CreatePropertyColumn_2(__builder2, 34, default(McpServerItem)!, 35, 
#nullable restore
#line (16,35)-(16,48) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
c=>c.Endpoint

#line default
#line hidden
#nullable disable
                , 36, "命令/地址", 37, (__builder3) => {
#nullable restore
#line (17,15)-(17,71) 26 "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
__builder3.AddContent(38, context.IsUrlServer ? context.Endpoint : context.Command

#line default
#line hidden
#nullable disable
                    );
                }
                );
                __builder2.AddMarkupContent(39, "\n        ");
                global::__Blazor.Alife.Function.Mcp.McpServiceUI.TypeInference.CreatePropertyColumn_3(__builder2, 40, default(McpServerItem)!, 41, 
#nullable restore
#line (19,35)-(19,51) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
c=>c.Description

#line default
#line hidden
#nullable disable
                , 42, "描述");
                __builder2.AddMarkupContent(43, "\n        ");
                global::__Blazor.Alife.Function.Mcp.McpServiceUI.TypeInference.CreatePropertyColumn_4(__builder2, 44, default(McpServerItem)!, 45, 
#nullable restore
#line (20,35)-(20,50) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
c=>c.IsImplicit

#line default
#line hidden
#nullable disable
                , 46, "渐进加载", 47, (__builder3) => {
                    __builder3.OpenComponent<global::AntDesign.Switch>(48);
                    __builder3.AddComponentParameter(49, nameof(global::AntDesign.Switch.
#nullable restore
#line (21,27)-(21,32) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Value

#line default
#line hidden
#nullable disable
                    ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (21,34)-(21,52) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
context.IsImplicit

#line default
#line hidden
#nullable disable
                    ));
                    __builder3.AddComponentParameter(50, nameof(global::AntDesign.Switch.ValueChanged), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::System.Boolean>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::System.Boolean>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => context.IsImplicit = __value, context.IsImplicit))));
                    __builder3.AddComponentParameter(51, nameof(global::AntDesign.Switch.ValueExpression), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Linq.Expressions.Expression<global::System.Func<global::System.Boolean>>>(() => context.IsImplicit));
                    __builder3.CloseComponent();
                }
                );
                __builder2.AddMarkupContent(52, "\n        ");
                global::__Blazor.Alife.Function.Mcp.McpServiceUI.TypeInference.CreatePropertyColumn_5(__builder2, 53, default(McpServerItem)!, 54, 
#nullable restore
#line (23,35)-(23,47) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
c=>c.Enabled

#line default
#line hidden
#nullable disable
                , 55, "启用", 56, (__builder3) => {
                    __builder3.OpenComponent<global::AntDesign.Switch>(57);
                    __builder3.AddComponentParameter(58, nameof(global::AntDesign.Switch.
#nullable restore
#line (24,27)-(24,32) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Value

#line default
#line hidden
#nullable disable
                    ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (24,34)-(24,49) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
context.Enabled

#line default
#line hidden
#nullable disable
                    ));
                    __builder3.AddComponentParameter(59, nameof(global::AntDesign.Switch.ValueChanged), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::System.Boolean>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::System.Boolean>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => context.Enabled = __value, context.Enabled))));
                    __builder3.AddComponentParameter(60, nameof(global::AntDesign.Switch.ValueExpression), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Linq.Expressions.Expression<global::System.Func<global::System.Boolean>>>(() => context.Enabled));
                    __builder3.CloseComponent();
                }
                );
                __builder2.AddMarkupContent(61, "\n        ");
                __builder2.OpenComponent<global::AntDesign.ActionColumn>(62);
                __builder2.AddComponentParameter(63, nameof(global::AntDesign.ActionColumn.
#nullable restore
#line (26,23)-(26,28) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Title

#line default
#line hidden
#nullable disable
                ), "操作");
                __builder2.AddAttribute(64, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder3) => {
                    __builder3.OpenComponent<global::AntDesign.Space>(65);
                    __builder3.AddAttribute(66, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder4) => {
                        __builder4.OpenComponent<global::AntDesign.SpaceItem>(67);
                        __builder4.AddAttribute(68, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder5) => {
                            __builder5.OpenComponent<global::AntDesign.Button>(69);
                            __builder5.AddComponentParameter(70, nameof(global::AntDesign.Button.
#nullable restore
#line (29,29)-(29,33) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Size

#line default
#line hidden
#nullable disable
                            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.ButtonSize>(
#nullable restore
#line (29,36)-(29,52) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
ButtonSize.Small

#line default
#line hidden
#nullable disable
                            ));
                            __builder5.AddComponentParameter(71, nameof(global::AntDesign.Button.
#nullable restore
#line (29,54)-(29,61) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
OnClick

#line default
#line hidden
#nullable disable
                            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::Microsoft.AspNetCore.Components.Web.MouseEventArgs>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line (29,65)-(29,90) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
() => EditServer(context)

#line default
#line hidden
#nullable disable
                            )));
                            __builder5.AddAttribute(72, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder6) => {
                                __builder6.AddMarkupContent(73, "编辑");
                            }
                            ));
                            __builder5.CloseComponent();
                        }
                        ));
                        __builder4.CloseComponent();
                        __builder4.AddMarkupContent(74, "\n                ");
                        __builder4.OpenComponent<global::AntDesign.SpaceItem>(75);
                        __builder4.AddAttribute(76, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder5) => {
                            __builder5.OpenComponent<global::AntDesign.Button>(77);
                            __builder5.AddComponentParameter(78, nameof(global::AntDesign.Button.
#nullable restore
#line (32,29)-(32,33) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Size

#line default
#line hidden
#nullable disable
                            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.ButtonSize>(
#nullable restore
#line (32,36)-(32,52) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
ButtonSize.Small

#line default
#line hidden
#nullable disable
                            ));
                            __builder5.AddComponentParameter(79, nameof(global::AntDesign.Button.
#nullable restore
#line (32,54)-(32,60) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Danger

#line default
#line hidden
#nullable disable
                            ), true);
                            __builder5.AddComponentParameter(80, nameof(global::AntDesign.Button.
#nullable restore
#line (32,61)-(32,68) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
OnClick

#line default
#line hidden
#nullable disable
                            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::Microsoft.AspNetCore.Components.Web.MouseEventArgs>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line (32,72)-(32,99) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
() => RemoveServer(context)

#line default
#line hidden
#nullable disable
                            )));
                            __builder5.AddAttribute(81, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder6) => {
                                __builder6.AddMarkupContent(82, "删除");
                            }
                            ));
                            __builder5.CloseComponent();
                        }
                        ));
                        __builder4.CloseComponent();
                    }
                    ));
                    __builder3.CloseComponent();
                }
                ));
                __builder2.CloseComponent();
            }
            ));
            __builder.CloseComponent();
            __builder.AddMarkupContent(83, "\n\n    ");
            __builder.OpenComponent<global::AntDesign.Drawer>(84);
            __builder.AddComponentParameter(85, nameof(global::AntDesign.Drawer.
#nullable restore
#line (38,13)-(38,18) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Title

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::OneOf.OneOf<global::Microsoft.AspNetCore.Components.RenderFragment, global::System.String>>(
#nullable restore
#line (38,22)-(38,29) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
"服务器配置"

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(86, nameof(global::AntDesign.Drawer.
#nullable restore
#line (39,13)-(39,20) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Visible

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (39,22)-(39,37) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
isEditingServer

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(87, nameof(global::AntDesign.Drawer.
#nullable restore
#line (40,13)-(40,18) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Width

#line default
#line hidden
#nullable disable
            ), "420");
            __builder.AddComponentParameter(88, nameof(global::AntDesign.Drawer.
#nullable restore
#line (41,13)-(41,20) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
OnClose

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create(this, 
#nullable restore
#line (41,22)-(41,33) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
CloseEditor

#line default
#line hidden
#nullable disable
            )));
            __builder.AddAttribute(89, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder2) => {
#nullable restore
#line (42,1)-(42,9) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
        

#line default
#line hidden
#nullable disable

#nullable restore
#line (42,10)-(44,1) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
if (editingServer != null)
        {

#line default
#line hidden
#nullable disable

                __builder2.OpenComponent<global::AntDesign.Form<
#nullable restore
#line (44,27)-(44,40) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
McpServerItem

#line default
#line hidden
#nullable disable
                >>(90);
                __builder2.AddComponentParameter(91, nameof(global::AntDesign.Form<McpServerItem>.
#nullable restore
#line (44,42)-(44,47) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Model

#line default
#line hidden
#nullable disable
                ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<McpServerItem>(
#nullable restore
#line (44,50)-(44,63) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
editingServer

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddComponentParameter(92, nameof(global::AntDesign.Form<McpServerItem>.
#nullable restore
#line (44,65)-(44,71) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Layout

#line default
#line hidden
#nullable disable
                ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.FormLayout>(
#nullable restore
#line (44,74)-(44,93) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
FormLayout.Vertical

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(93, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment<McpServerItem>)((context) => (__builder3) => {
                    __builder3.OpenComponent<global::AntDesign.FormItem>(94);
                    __builder3.AddComponentParameter(95, nameof(global::AntDesign.FormItem.
#nullable restore
#line (45,27)-(45,32) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Label

#line default
#line hidden
#nullable disable
                    ), "名称");
                    __builder3.AddAttribute(96, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder4) => {
                        global::__Blazor.Alife.Function.Mcp.McpServiceUI.TypeInference.CreateInput_6(__builder4, 97, 98, 
#nullable restore
#line (46,41)-(46,59) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
editingServer.Name

#line default
#line hidden
#nullable disable
                        , 99, global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => editingServer.Name = __value, editingServer.Name)), 100, () => editingServer.Name);
                    }
                    ));
                    __builder3.CloseComponent();
                    __builder3.AddMarkupContent(101, "\n                ");
                    __builder3.OpenComponent<global::AntDesign.FormItem>(102);
                    __builder3.AddComponentParameter(103, nameof(global::AntDesign.FormItem.
#nullable restore
#line (48,27)-(48,32) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Label

#line default
#line hidden
#nullable disable
                    ), "描述");
                    __builder3.AddAttribute(104, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder4) => {
                        global::__Blazor.Alife.Function.Mcp.McpServiceUI.TypeInference.CreateInput_7(__builder4, 105, 106, 
#nullable restore
#line (49,41)-(49,66) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
editingServer.Description

#line default
#line hidden
#nullable disable
                        , 107, global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => editingServer.Description = __value, editingServer.Description)), 108, () => editingServer.Description);
                    }
                    ));
                    __builder3.CloseComponent();
                    __builder3.AddMarkupContent(109, "\n                ");
                    __builder3.OpenComponent<global::AntDesign.FormItem>(110);
                    __builder3.AddComponentParameter(111, nameof(global::AntDesign.FormItem.
#nullable restore
#line (51,27)-(51,32) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Label

#line default
#line hidden
#nullable disable
                    ), "连接方式");
                    __builder3.AddAttribute(112, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder4) => {
                        __builder4.OpenComponent<global::AntDesign.Segmented<
#nullable restore
#line (52,40)-(52,46) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
string

#line default
#line hidden
#nullable disable
                        >>(113);
                        __builder4.AddComponentParameter(114, nameof(global::AntDesign.Segmented<string>.
#nullable restore
#line (53,32)-(53,37) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Value

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<string>(
#nullable restore
#line (53,41)-(53,68) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
isUrlType ? "url" : "local"

#line default
#line hidden
#nullable disable
                        ));
                        __builder4.AddComponentParameter(115, nameof(global::AntDesign.Segmented<string>.
#nullable restore
#line (54,32)-(54,44) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
ValueChanged

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<string>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<string>(this, 
#nullable restore
#line (54,47)-(54,60) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
OnTypeChanged

#line default
#line hidden
#nullable disable
                        )));
                        __builder4.AddComponentParameter(116, nameof(global::AntDesign.Segmented<string>.
#nullable restore
#line (55,32)-(55,37) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Block

#line default
#line hidden
#nullable disable
                        ), true);
                        __builder4.AddAttribute(117, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder5) => {
                            global::__Blazor.Alife.Function.Mcp.McpServiceUI.TypeInference.CreateSegmentedItem_8(__builder5, 118, 119, 
#nullable restore
#line (56,49)-(56,56) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
"local"

#line default
#line hidden
#nullable disable
                            , 120, "本地命令");
                            __builder5.AddMarkupContent(121, "\n                        ");
                            global::__Blazor.Alife.Function.Mcp.McpServiceUI.TypeInference.CreateSegmentedItem_9(__builder5, 122, 123, 
#nullable restore
#line (57,49)-(57,54) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
"url"

#line default
#line hidden
#nullable disable
                            , 124, "URL 服务");
                        }
                        ));
                        __builder4.CloseComponent();
                    }
                    ));
                    __builder3.CloseComponent();
#nullable restore
#line (61,1)-(61,17) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
                

#line default
#line hidden
#nullable disable

#nullable restore
#line (61,18)-(63,1) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
if (isUrlType)
                {

#line default
#line hidden
#nullable disable

                    __builder3.OpenComponent<global::AntDesign.FormItem>(125);
                    __builder3.AddComponentParameter(126, nameof(global::AntDesign.FormItem.
#nullable restore
#line (63,31)-(63,36) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Label

#line default
#line hidden
#nullable disable
                    ), "服务器地址 (URL)");
                    __builder3.AddAttribute(127, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder4) => {
                        global::__Blazor.Alife.Function.Mcp.McpServiceUI.TypeInference.CreateInput_10(__builder4, 128, 129, "如 http://127.0.0.1:18765/mcp", 130, 
#nullable restore
#line (64,45)-(64,67) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
editingServer.Endpoint

#line default
#line hidden
#nullable disable
                        , 131, global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => editingServer.Endpoint = __value, editingServer.Endpoint)), 132, () => editingServer.Endpoint);
                    }
                    ));
                    __builder3.CloseComponent();
#nullable restore
#line (66,1)-(69,1) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
                }
                else
                {

#line default
#line hidden
#nullable disable

                    __builder3.OpenComponent<global::AntDesign.FormItem>(133);
                    __builder3.AddComponentParameter(134, nameof(global::AntDesign.FormItem.
#nullable restore
#line (69,31)-(69,36) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Label

#line default
#line hidden
#nullable disable
                    ), "可执行文件 (Command)");
                    __builder3.AddAttribute(135, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder4) => {
                        global::__Blazor.Alife.Function.Mcp.McpServiceUI.TypeInference.CreateInput_11(__builder4, 136, 137, 
#nullable restore
#line (70,45)-(70,66) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
editingServer.Command

#line default
#line hidden
#nullable disable
                        , 138, global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => editingServer.Command = __value, editingServer.Command)), 139, () => editingServer.Command);
                    }
                    ));
                    __builder3.CloseComponent();
                    __builder3.AddMarkupContent(140, "\n                    ");
                    __builder3.OpenComponent<global::AntDesign.FormItem>(141);
                    __builder3.AddComponentParameter(142, nameof(global::AntDesign.FormItem.
#nullable restore
#line (72,31)-(72,36) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Label

#line default
#line hidden
#nullable disable
                    ), "参数 (每个参数一行)");
                    __builder3.AddAttribute(143, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder4) => {
                        __builder4.OpenComponent<global::AntDesign.TextArea>(144);
                        __builder4.AddComponentParameter(145, nameof(global::AntDesign.TextArea.
#nullable restore
#line (73,35)-(73,40) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Value

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (73,43)-(73,85) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
string.Join('\n', editingServer.Arguments)

#line default
#line hidden
#nullable disable
                        ));
                        __builder4.AddComponentParameter(146, nameof(global::AntDesign.TextArea.
#nullable restore
#line (74,35)-(74,47) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
ValueChanged

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::System.String>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::System.String>(this, 
#nullable restore
#line (74,51)-(74,138) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
val => editingServer.Arguments = val.Split('\n', StringSplitOptions.RemoveEmptyEntries)

#line default
#line hidden
#nullable disable
                        )));
                        __builder4.AddComponentParameter(147, nameof(global::AntDesign.TextArea.
#nullable restore
#line (75,35)-(75,39) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Rows

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.UInt32>(
#nullable restore
#line (75,41)-(75,42) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
4

#line default
#line hidden
#nullable disable
                        ));
                        __builder4.CloseComponent();
                    }
                    ));
                    __builder3.CloseComponent();
#nullable restore
#line (77,1)-(78,1) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
                }

#line default
#line hidden
#nullable disable

                    __builder3.OpenComponent<global::AntDesign.FormItem>(148);
                    __builder3.AddAttribute(149, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder4) => {
                        __builder4.OpenComponent<global::AntDesign.Button>(150);
                        __builder4.AddComponentParameter(151, nameof(global::AntDesign.Button.
#nullable restore
#line (80,29)-(80,33) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Type

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.ButtonType?>(
#nullable restore
#line (80,36)-(80,54) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
ButtonType.Primary

#line default
#line hidden
#nullable disable
                        ));
                        __builder4.AddComponentParameter(152, nameof(global::AntDesign.Button.
#nullable restore
#line (80,56)-(80,63) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
OnClick

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::Microsoft.AspNetCore.Components.Web.MouseEventArgs>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line (80,65)-(80,76) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
CloseEditor

#line default
#line hidden
#nullable disable
                        )));
                        __builder4.AddComponentParameter(153, nameof(global::AntDesign.Button.
#nullable restore
#line (80,78)-(80,83) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Block

#line default
#line hidden
#nullable disable
                        ), true);
                        __builder4.AddAttribute(154, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder5) => {
                            __builder5.AddMarkupContent(155, "完成");
                        }
                        ));
                        __builder4.CloseComponent();
                    }
                    ));
                    __builder3.CloseComponent();
                }
                ));
                __builder2.CloseComponent();
#nullable restore
#line (83,1)-(84,1) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
        }

#line default
#line hidden
#nullable disable

            }
            ));
            __builder.CloseComponent();
            __builder.CloseElement();
        }
        #pragma warning restore 1998
#nullable restore
#line (87,8)-(130,1) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"


    McpServerItem? editingServer;
    bool isEditingServer;
    bool isUrlType;

    void AddServer()
    {
        editingServer = new McpServerItem();
        Configuration.Servers.Add(editingServer);
        isUrlType = false;
        isEditingServer = true;
    }

    void EditServer(McpServerItem server)
    {
        editingServer = server;
        isUrlType = server.IsUrlServer;
        isEditingServer = true;
    }

    void RemoveServer(McpServerItem server)
    {
        Configuration.Servers.Remove(server);
    }

    void OnTypeChanged(string value)
    {
        if (editingServer == null)
            return;

        isUrlType = value == "url";
        //切换连接方式时清空另一种方式填写的配置，避免歧义
        if (isUrlType)
            editingServer.Command = "";
        else
            editingServer.Endpoint = "";
    }

    void CloseEditor()
    {
        isEditingServer = false;
    }

#line default
#line hidden
#nullable disable

    }
}
namespace __Blazor.Alife.Function.Mcp.McpServiceUI
{
    #line hidden
    internal static class TypeInference
    {
        public static void CreatePropertyColumn_0<TItem, TProp>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, TItem __syntheticArg0, int __seq0, global::System.Linq.Expressions.Expression<global::System.Func<TItem, TProp>> __arg0, int __seq1, global::System.String __arg1)
        {
        __builder.OpenComponent<global::AntDesign.PropertyColumn<TItem, TProp>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::AntDesign.PropertyColumn<TItem, TProp>.
#nullable restore
#line (12,25)-(12,33) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Property

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, nameof(global::AntDesign.PropertyColumn<TItem, TProp>.
#nullable restore
#line (12,46)-(12,51) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Title

#line default
#line hidden
#nullable disable
        ), __arg1);
        __builder.CloseComponent();
        }
        public static void CreatePropertyColumn_1<TItem, TProp>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, TItem __syntheticArg0, int __seq0, global::System.Linq.Expressions.Expression<global::System.Func<TItem, TProp>> __arg0, int __seq1, global::System.String __arg1, int __seq2, global::Microsoft.AspNetCore.Components.RenderFragment __arg2)
        {
        __builder.OpenComponent<global::AntDesign.PropertyColumn<TItem, TProp>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::AntDesign.PropertyColumn<TItem, TProp>.
#nullable restore
#line (13,25)-(13,33) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Property

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, nameof(global::AntDesign.PropertyColumn<TItem, TProp>.
#nullable restore
#line (13,53)-(13,58) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Title

#line default
#line hidden
#nullable disable
        ), __arg1);
        __builder.AddComponentParameter(__seq2, "ChildContent", __arg2);
        __builder.CloseComponent();
        }
        public static void CreatePropertyColumn_2<TItem, TProp>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, TItem __syntheticArg0, int __seq0, global::System.Linq.Expressions.Expression<global::System.Func<TItem, TProp>> __arg0, int __seq1, global::System.String __arg1, int __seq2, global::Microsoft.AspNetCore.Components.RenderFragment __arg2)
        {
        __builder.OpenComponent<global::AntDesign.PropertyColumn<TItem, TProp>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::AntDesign.PropertyColumn<TItem, TProp>.
#nullable restore
#line (16,25)-(16,33) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Property

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, nameof(global::AntDesign.PropertyColumn<TItem, TProp>.
#nullable restore
#line (16,50)-(16,55) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Title

#line default
#line hidden
#nullable disable
        ), __arg1);
        __builder.AddComponentParameter(__seq2, "ChildContent", __arg2);
        __builder.CloseComponent();
        }
        public static void CreatePropertyColumn_3<TItem, TProp>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, TItem __syntheticArg0, int __seq0, global::System.Linq.Expressions.Expression<global::System.Func<TItem, TProp>> __arg0, int __seq1, global::System.String __arg1)
        {
        __builder.OpenComponent<global::AntDesign.PropertyColumn<TItem, TProp>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::AntDesign.PropertyColumn<TItem, TProp>.
#nullable restore
#line (19,25)-(19,33) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Property

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, nameof(global::AntDesign.PropertyColumn<TItem, TProp>.
#nullable restore
#line (19,53)-(19,58) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Title

#line default
#line hidden
#nullable disable
        ), __arg1);
        __builder.CloseComponent();
        }
        public static void CreatePropertyColumn_4<TItem, TProp>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, TItem __syntheticArg0, int __seq0, global::System.Linq.Expressions.Expression<global::System.Func<TItem, TProp>> __arg0, int __seq1, global::System.String __arg1, int __seq2, global::Microsoft.AspNetCore.Components.RenderFragment __arg2)
        {
        __builder.OpenComponent<global::AntDesign.PropertyColumn<TItem, TProp>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::AntDesign.PropertyColumn<TItem, TProp>.
#nullable restore
#line (20,25)-(20,33) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Property

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, nameof(global::AntDesign.PropertyColumn<TItem, TProp>.
#nullable restore
#line (20,52)-(20,57) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Title

#line default
#line hidden
#nullable disable
        ), __arg1);
        __builder.AddComponentParameter(__seq2, "ChildContent", __arg2);
        __builder.CloseComponent();
        }
        public static void CreatePropertyColumn_5<TItem, TProp>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, TItem __syntheticArg0, int __seq0, global::System.Linq.Expressions.Expression<global::System.Func<TItem, TProp>> __arg0, int __seq1, global::System.String __arg1, int __seq2, global::Microsoft.AspNetCore.Components.RenderFragment __arg2)
        {
        __builder.OpenComponent<global::AntDesign.PropertyColumn<TItem, TProp>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::AntDesign.PropertyColumn<TItem, TProp>.
#nullable restore
#line (23,25)-(23,33) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Property

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, nameof(global::AntDesign.PropertyColumn<TItem, TProp>.
#nullable restore
#line (23,49)-(23,54) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Title

#line default
#line hidden
#nullable disable
        ), __arg1);
        __builder.AddComponentParameter(__seq2, "ChildContent", __arg2);
        __builder.CloseComponent();
        }
        public static void CreateInput_6<TValue>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, TValue __arg0, int __seq1, global::Microsoft.AspNetCore.Components.EventCallback<TValue> __arg1, int __seq2, global::System.Linq.Expressions.Expression<global::System.Func<TValue>> __arg2)
        {
        __builder.OpenComponent<global::AntDesign.Input<TValue>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::AntDesign.Input<TValue>.
#nullable restore
#line (46,34)-(46,39) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Value

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, nameof(global::AntDesign.Input<TValue>.ValueChanged), __arg1);
        __builder.AddComponentParameter(__seq2, nameof(global::AntDesign.Input<TValue>.ValueExpression), __arg2);
        __builder.CloseComponent();
        }
        public static void CreateInput_7<TValue>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, TValue __arg0, int __seq1, global::Microsoft.AspNetCore.Components.EventCallback<TValue> __arg1, int __seq2, global::System.Linq.Expressions.Expression<global::System.Func<TValue>> __arg2)
        {
        __builder.OpenComponent<global::AntDesign.Input<TValue>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::AntDesign.Input<TValue>.
#nullable restore
#line (49,34)-(49,39) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Value

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, nameof(global::AntDesign.Input<TValue>.ValueChanged), __arg1);
        __builder.AddComponentParameter(__seq2, nameof(global::AntDesign.Input<TValue>.ValueExpression), __arg2);
        __builder.CloseComponent();
        }
        public static void CreateSegmentedItem_8<TValue>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, TValue __arg0, int __seq1, global::System.String __arg1)
        {
        __builder.OpenComponent<global::AntDesign.SegmentedItem<TValue>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::AntDesign.SegmentedItem<TValue>.
#nullable restore
#line (56,40)-(56,45) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Value

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, nameof(global::AntDesign.SegmentedItem<TValue>.
#nullable restore
#line (56,59)-(56,64) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Label

#line default
#line hidden
#nullable disable
        ), __arg1);
        __builder.CloseComponent();
        }
        public static void CreateSegmentedItem_9<TValue>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, TValue __arg0, int __seq1, global::System.String __arg1)
        {
        __builder.OpenComponent<global::AntDesign.SegmentedItem<TValue>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::AntDesign.SegmentedItem<TValue>.
#nullable restore
#line (57,40)-(57,45) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Value

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, nameof(global::AntDesign.SegmentedItem<TValue>.
#nullable restore
#line (57,57)-(57,62) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Label

#line default
#line hidden
#nullable disable
        ), __arg1);
        __builder.CloseComponent();
        }
        public static void CreateInput_10<TValue>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, global::System.String __arg0, int __seq1, TValue __arg1, int __seq2, global::Microsoft.AspNetCore.Components.EventCallback<TValue> __arg2, int __seq3, global::System.Linq.Expressions.Expression<global::System.Func<TValue>> __arg3)
        {
        __builder.OpenComponent<global::AntDesign.Input<TValue>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::AntDesign.Input<TValue>.
#nullable restore
#line (64,69)-(64,80) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Placeholder

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, nameof(global::AntDesign.Input<TValue>.
#nullable restore
#line (64,38)-(64,43) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Value

#line default
#line hidden
#nullable disable
        ), __arg1);
        __builder.AddComponentParameter(__seq2, nameof(global::AntDesign.Input<TValue>.ValueChanged), __arg2);
        __builder.AddComponentParameter(__seq3, nameof(global::AntDesign.Input<TValue>.ValueExpression), __arg3);
        __builder.CloseComponent();
        }
        public static void CreateInput_11<TValue>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, TValue __arg0, int __seq1, global::Microsoft.AspNetCore.Components.EventCallback<TValue> __arg1, int __seq2, global::System.Linq.Expressions.Expression<global::System.Func<TValue>> __arg2)
        {
        __builder.OpenComponent<global::AntDesign.Input<TValue>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::AntDesign.Input<TValue>.
#nullable restore
#line (70,38)-(70,43) "C:\Users\13309\Desktop\Alife\sources\Alife.Function\Alife.Function.Mcp\McpServiceUI.razor"
Value

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, nameof(global::AntDesign.Input<TValue>.ValueChanged), __arg1);
        __builder.AddComponentParameter(__seq2, nameof(global::AntDesign.Input<TValue>.ValueExpression), __arg2);
        __builder.CloseComponent();
        }
    }
}
#pragma warning restore 1591
